DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS users;

CREATE TABLE books (
id      SERIAL PRIMARY KEY,
isbn    VARCHAR NOT NULL,
title   VARCHAR NOT NULL,
author  VARCHAR NOT NULL,
year    INTEGER NOT NULL
);

CREATE TABLE reviews (
id      SERIAL PRIMARY KEY,
book_id INTEGER REFERENCES books,
user_id INTEGER REFERENCES users,
body    VARCHAR NOT NULL,
created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
id       SERIAL PRIMARY KEY,
name     VARCHAR NOT NULL,
password VARCHAR NOT NULL,
email    VARCHAR NOT NULL
);